export const THEMES = [
  'aliens',
  'animals',
  'cooking',
  'crossdressing',
  'deliquents',
  'demons',
  'genderswap',
  'ghosts',
  'gyaru',
  'harem',
  'incest',
  'loli',
  'mafia',
  'magic',
  'martial arts',
  'military',
  'monster girls',
  'monsters',
  'music',
  'ninja',
  'office workers',
  'police',
  'post-apocalyptic',
  'reincarnation',
  'reverse harem',
  'samurai',
  'school life',
  'shota',
  'supernatural',
  'survival',
  'time travel',
  'traditional games',
  'vampires',
  'video games',
  'villainess',
  'virtual reality',
  'zombies',
];
