export const TITLES = 'titles';

export const genres = [
  'action',
  'adventure',
  "boys' love",
  'comedy',
  'crime',
  'drama',
  'fantasy',
  "girls' love",
  'historical',
  'horror',
  'isekai',
  'magical girls',
  'mecha',
  'medical',
  'mystery',
  'philosophical',
  'psychological',
  'romance',
  'sci-fi',
  'slice of life',
  'sports',
  'superhero',
  'thriller',
  'tragedy',
  'wuxia'
];

export const themes = [
  'aliens',
  'animals',
  'cooking',
  'crossdressing',
  'deliquents',
  'demons',
  'genderswap',
  'ghosts',
  'gyaru',
  'harem',
  'incest',
  'loli',
  'mafia',
  'magic',
  'martial arts',
  'military',
  'monster girls',
  'monsters',
  'music',
  'ninja',
  'office workers',
  'police',
  'post-apocalyptic',
  'reincarnation',
  'reverse harem',
  'samurai',
  'school life',
  'shota',
  'supernatural',
  'survival',
  'time travel',
  'traditional games',
  'vampires',
  'video games',
  'villainess',
  'virtual reality',
  'zombies'
];

export const mangaType = ['manga', 'manhwa', 'manhua'];
